CODE_SUCCESS = {"code": "SUCCESS"}
CODE_WAIT = {"code": "WAIT"}
CODE_FAILURE = {"code": "FAILURE"}

MSG_DB_FAILED = "Failed to handle DB requests."
MSG_NOT_MATCHED = "There is no matched data"
MSG_NOT_MATCHED_DEVICE = "There is no matched device"
MSG_NOT_FOUND = "The data is not found."
MSG_NO_DATA = "There is no data."
MSG_NO_REQUEST_DATA = "There is no request data."
MSG_INVALID_PARAMETER = "Invalid Parameter"
MSG_INVALID_USER = "Invalid User"
MSG_UNKNOWN_ERROR = "Unknown error."
MSG_INSERT_ERROR = "To insert data failed."
# MSG_UPDATE_ERROR = "To update data failed."
MSG_UPDATE_ERROR = "To update data failed. Data is not changed."
MSG_DELETE_ERROR = "To delete data failed."
MSG_NO_CHANGE = "There is no change."
MSG_CONN_FAILED = "Connection is failed."
MSG_ID_ALREADY_EXISTED = "This user id is already existed."
